# ECE4782 Deep Learning Labs
## 0. Introduction to PyTorch

In this chapter, we will learn basic usage of PyTorch.
There are many good tutorials on PyTorch on web.
We highly recommend you to follow the official [tutorial](http://pytorch.org/tutorials/) even though this tutorial is also mainly from it.

### Import

After installing PyTorch, you can import `torch` in Python to use PyTorch.

In [1]:
import torch

Let's check the version of PyTorch, and it should be 1.0 or higher.

In [2]:
print(torch.__version__)

1.7.0


### Tensor Creation

PyTorch is very similar with Numpy as they say it is a replacement for Numpy to use the power of GPUs. Although there are still missing components, it has many same/similar functions for constructing or manipulating 'Tensor's.

A basic object used in PyTorch is 'Tensor' which is equivalent to 'ndarray' in Numpy. Similarly to Numpy, there are multiple types of Tensors, e.g. Float, Double, Int, Long, etc. Most of time, however, we will use FloatTensor mainly (and it is a default type for the most of functions) to utilize GPU and LongTensor sometime for target/label values.

Lets try to create a Tensor. If you call `torch.Tensor(rows, cols)`, it will return a FloatTensor without initialization (with garbage values).

In [3]:
x = torch.Tensor(5, 3) # same result with torch.FloatTensor(5,3)
x

tensor([[-4.1273e+34,  4.5797e-41, -4.1273e+34],
        [ 4.5797e-41,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  2.4616e-38],
        [ 1.0006e-34, -1.7546e+38,  2.4617e-38],
        [ 1.0006e-34, -1.7546e+38,  2.4617e-38]])

Similar to `numpy.ndarray()`, you can create a Tensro with values using `torch.tensor(values)`.

In [4]:
x_manual = torch.tensor([[1.0, 2.0], [3.0, 4.0]])
x_manual

tensor([[1., 2.],
        [3., 4.]])

Also, you can create an initialized Tensor filled with 1s, 0s, or random numbers from a uniform distribtution by using `torch.ones`, `torch.zeros`, or `torch.rand` repectively.

In [5]:
x_ones = torch.ones(5,3)
print(x_ones)

x_zeros = torch.zeros(5,3)
print(x_zeros)

x_uniform = torch.rand(5,3)
print(x_uniform)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[0.1148, 0.7743, 0.3082],
        [0.1033, 0.1723, 0.2544],
        [0.5038, 0.4549, 0.1847],
        [0.1797, 0.3905, 0.2119],
        [0.3194, 0.0607, 0.4407]])


### Exercise: Try `torch.eye`, `torch.linspace`, `torch.logspace`, etc.
### Exercise: Try other random functions from [here](http://pytorch.org/docs/master/torch.html#random-sampling)

### Converting from/to Numpy ndarray

You can also create a Tensor from Numpy ndarray or vice versa. In fact, we may do this many times in a project since we want to utilize many Numpy-based libraries (e.g., Pandas, Scikit-learn, Matplotlib, etc.) as well as GPU computation.

You can simply call `torch.from_numpy(ndarray)` to create a `Tensor` from a `numpy.ndarray`. **Be careful that the returned Tensor and original ndarray share the same memory**. Therefore, if you modify the Tensor, it will be reflected in the ndarray.

In [6]:
import numpy as np
np_array = np.array([1., 2., 3.], dtype=np.float32)  # set dtype=np.float32 to get a FloatTensor
print(np_array)
torch_tensor = torch.from_numpy(np_array)
print(torch_tensor)

# Modify the Tensor
torch_tensor[0] = -1.0
print(torch_tensor)
# np_array has also been modified
print(np_array)

[1. 2. 3.]
tensor([1., 2., 3.])
tensor([-1.,  2.,  3.])
[-1.  2.  3.]


For the reverse way of conversion, you can call `numpy()` on a Tensor. Again, resulting ndarray shares the memory with the Tensor.

In [7]:
another_torch_tensor = torch.rand(3)
print(another_torch_tensor)
another_np_array = another_torch_tensor.numpy()
print(another_np_array)

# Modify ndarray
another_np_array[0] *= 2.0
print(another_torch_tensor)

tensor([0.1638, 0.9285, 0.9775])
[0.16379583 0.9285188  0.9774868 ]
tensor([0.3276, 0.9285, 0.9775])


To extract the value from a single-element Tensor, e.g., Tensor storing a loss value, you can use `item()` on a Tensor.

In [8]:
single_element_tensor = torch.Tensor([1.23])
print(single_element_tensor)
single_value = single_element_tensor.item()
print(single_value)

tensor([1.2300])
1.2300000190734863


### Basic Operations

#### Indexing

You can use standard numpy-like indexing.

In [9]:
A = torch.rand(3,3)
print(A)
print(A[:, 1])  # get the 1st column
print(A[:2, :])  # get the rows upto the 2nd row

tensor([[0.7638, 0.8654, 0.1224],
        [0.5612, 0.2198, 0.8788],
        [0.5316, 0.8183, 0.1758]])
tensor([0.8654, 0.2198, 0.8183])
tensor([[0.7638, 0.8654, 0.1224],
        [0.5612, 0.2198, 0.8788]])


#### Arithmetic Operations
Arithmetic operations with `+-*/` operators are all element-wise computation. Therefore, if you want to do some matrix computations such as matrix-matrix (or vector) multiplication, you need to call separate functions.  

In [10]:
B = torch.rand(3,3)
print(A+B)
print(A*B)
# Another elementwise multiplication
print(torch.mul(A,B))

# Matrix-Matrix multiplication
print(torch.mm(A,B))
# Matrix-Vector multiplication
print(torch.mv(A,B[:,1]))

tensor([[1.5139, 1.5047, 0.9288],
        [0.7959, 0.7002, 1.2052],
        [1.3073, 0.9849, 0.2062]])
tensor([[0.5729, 0.5532, 0.0987],
        [0.1317, 0.1056, 0.2869],
        [0.4124, 0.1364, 0.0053]])
tensor([[0.5729, 0.5532, 0.0987],
        [0.1317, 0.1056, 0.2869],
        [0.4124, 0.1364, 0.0053]])
tensor([[0.8710, 0.9244, 0.9021],
        [1.1541, 0.6108, 0.5509],
        [0.7272, 0.7623, 0.7011]])
tensor([0.9244, 0.6108, 0.7623])


There are many predefined operations for your convenience such as batch multiplication with addition, etc. Please read [PyTorch Docs](http://pytorch.org/docs/master/torch.html#math-operations) for more information.

### GPU Acceleration

If we have NVIDIA GPU(s), we can accelerate computation once we move Tensors onto GPU.
Let's compare how much GPU can accelerate especially matrix operations.
We will do a matrix-matrix multiplication between two 5k-by-5k matrices on both CPU and GPU.

In [11]:
mat_cpu = torch.rand(5000, 5000)
mat_cpu

tensor([[0.6343, 0.7628, 0.0494,  ..., 0.5709, 0.1382, 0.1238],
        [0.3922, 0.4453, 0.4311,  ..., 0.6262, 0.3250, 0.3256],
        [0.7474, 0.6676, 0.0775,  ..., 0.0046, 0.9531, 0.2959],
        ...,
        [0.7031, 0.9385, 0.3263,  ..., 0.9100, 0.7963, 0.0499],
        [0.0322, 0.5315, 0.8714,  ..., 0.3195, 0.9964, 0.0535],
        [0.6153, 0.2484, 0.5867,  ..., 0.6081, 0.2686, 0.8339]])

In [12]:
mat_cpu.size()

torch.Size([5000, 5000])

In [13]:
%%time
torch.mm(mat_cpu.t(), mat_cpu)

CPU times: user 9.14 s, sys: 119 ms, total: 9.26 s
Wall time: 471 ms


tensor([[1667.5663, 1248.1425, 1258.7482,  ..., 1263.5630, 1261.4197,
         1248.0945],
        [1248.1425, 1648.9117, 1250.1246,  ..., 1259.4060, 1258.2202,
         1249.4613],
        [1258.7482, 1250.1246, 1685.4553,  ..., 1269.0441, 1269.0958,
         1252.4832],
        ...,
        [1263.5630, 1259.4060, 1269.0441,  ..., 1695.8975, 1278.3766,
         1271.1479],
        [1261.4197, 1258.2202, 1269.0958,  ..., 1278.3766, 1688.2131,
         1270.9777],
        [1248.0947, 1249.4614, 1252.4835,  ..., 1271.1489, 1270.9774,
         1673.6877]])

#### We need a GPU for this comparison
We can check its availability like:

In [14]:
if torch.cuda.is_available():
    cuda = True
else:
    cuda = False
cuda

True

In [15]:
mat_gpu = torch.rand(5000, 5000)
if cuda:
    mat_gpu = mat_gpu.cuda()
mat_gpu

tensor([[0.9610, 0.1546, 0.0310,  ..., 0.5290, 0.9918, 0.6340],
        [0.0140, 0.1544, 0.9732,  ..., 0.5830, 0.4201, 0.1951],
        [0.1215, 0.7262, 0.1614,  ..., 0.1479, 0.0562, 0.0883],
        ...,
        [0.0563, 0.4831, 0.2172,  ..., 0.0013, 0.8376, 0.6712],
        [0.2284, 0.4651, 0.5444,  ..., 0.8824, 0.0264, 0.0674],
        [0.1936, 0.2722, 0.8933,  ..., 0.3931, 0.7752, 0.5266]],
       device='cuda:0')

In [16]:
mat_gpu.size()

torch.Size([5000, 5000])

In [17]:
%%time
torch.mm(mat_gpu.t(), mat_gpu)

CPU times: user 258 ms, sys: 140 ms, total: 398 ms
Wall time: 401 ms


tensor([[1652.2537, 1228.5844, 1253.0370,  ..., 1253.6337, 1233.3325,
         1237.5886],
        [1228.5844, 1637.1395, 1243.2102,  ..., 1254.5740, 1219.7964,
         1239.2603],
        [1253.0370, 1243.2102, 1675.8785,  ..., 1263.1997, 1234.4841,
         1249.9261],
        ...,
        [1253.6337, 1254.5740, 1263.1997,  ..., 1667.6693, 1246.9858,
         1256.8524],
        [1233.3325, 1219.7964, 1234.4841,  ..., 1246.9858, 1642.3518,
         1242.8170],
        [1237.5886, 1239.2603, 1249.9261,  ..., 1256.8524, 1242.8170,
         1677.3129]], device='cuda:0')

Can you see the speed-up? It will be much critical if we use larger matrices, more matrix computations, and a deeper neural network model.

### ~~Variable~~ Autograd

**Variable wrapping is deprecated from PyTorch 0.4.** You can use just regular Tensor to use autograd functionality, and you can control the flag `requires_grad` in the Tensor. 

PyTorch provide a functionality of automatic differentiation with a package `autograd` and now `torch.Tensor` (instead of `Variable` in the old versions) is the key class for utilizing it.

A Tensor keeps its value and the gradient with respect to this Tensor value. Also, almost all of built-in operations in PyTorch supports automatic differentiation. Therefore, we can call `.backward()` on a computation graph, e.g. neural network, after we finish our computation on the graph, then we can get automatically accumulated gradient for each Tensor (which has `requires_grad=True`) related with the graph.

Let's try a simple example for easier understanding.

#### old code using Variable

```python
from torch.autograd import Variable

# Create some Tensors and a Variable
x = Variable(torch.FloatTensor([2.0]), requires_grad=False)
w = Variable(torch.FloatTensor([0.5]), requires_grad=True)
b = Variable(torch.FloatTensor([0.1]), requires_grad=True)
print(x)
print(w)
print(b)

# Define a computational graph
y = w*x + b # Currently, y = 0.5x + 0.1 and y(2) = 1.1
print(y)
```

#### Current one with PyTorch >= 0.4

In [18]:
# Create some Tensors
x = torch.tensor(2.0, requires_grad=False)
w = torch.tensor(0.5, requires_grad=True)
b = torch.tensor(0.1, requires_grad=True)
print(x)
print(w)
print(b)

# Define a computational graph
y = w*x + b # Currently, y = 0.5x + 0.1 and y(2) = 1.1
print(y)

tensor(2.)
tensor(0.5000, requires_grad=True)
tensor(0.1000, requires_grad=True)
tensor(1.1000, grad_fn=<AddBackward0>)


Let's compute gradients on the graph y and print the gradient w.r.t each Variable.

In [19]:
# Compute gradients
y.backward()

print(x.grad)
print(w.grad)
print(b.grad)

None
tensor(2.)
tensor(1.)


Since we set `requires_grad=False` for Tensor `x`, it has `None` value.
Also, if we do a simple math to differentiate it manually, we can easily get:
$$
\frac{\partial y}{\partial w} = \frac{\partial}{\partial w}\left(wx + b\right) = x\\
\text{and}\\
\displaystyle \frac{\partial y}{\partial w}\Bigr|_{x=2} = 2 
$$
Similarly,
$$
\frac{\partial y}{\partial b} = \frac{\partial}{\partial b}\left(wx + b\right) = 1\\
\text{and}\\
\displaystyle \frac{\partial y}{\partial b}\Bigr|_{x=2} = 1 
$$

Thanks to the functionality of automatic differentiation, we can build a very complex computational graph such as a neural network with many layers without manually computing the gradients of parameters.

Please refer to the official [tutorial](https://pytorch.org/tutorials/beginner/blitz/autograd_tutorial.html) for more details.

In the next chapter, we will build a simple feed-forward neural network by using these components of PyTorch we have learnt.